app = "iterascope"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  # WebGPU requires a secure browser context.
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

  [[http_service.checks]]
    grace_period = "5s"
    interval = "30s"
    method = "GET"
    path = "/"
    protocol = "http"
    timeout = "5s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  cpus = 1
